version: '3'

services:
  api:
    build: ./api
    image: thepiperpied/ems:0.0.1
    ports:
      - "3002:3002"
    volumes:
      - ./api:/app
    command: ["npm", "run", "start-dev"]
    links: 
      - db
    depends_on:
      - db

  db:
    build: ./db
    image: thepiperpied/ems-db:0.0.1
    ports:
      - "7575:7575"
      - "7688:7688"
    command: ["neo4j"]